### ISSUE TITLE
AV still alerting?

### ISSUE THREAD

**Issue by est31** [minetest/minetest.github.io#27] opened 2015-09-01 14:32 UTC
PoignardAzur from the forums reports they still get AV warnings when visiting the website.
https://forum.minetest.net/viewtopic.php?f=6&t=13153

**Comment by ShadowNinja** [comment] 2015-09-11 21:38
My best guess as to the cause of the warning is this:
`inchra-stats.minetest.net` is a `CNAME` for `stats.inchra.net`, which is a `CNAME` for `amun.inchra.net`, which contains `A`/`AAAA`/etc records.  Avast must be resolving the `CNAME`s and checking the resulting domain name instead of the original domain name.

If this guess is correct some solutions would be:
  * Copy all the `amun.inchra.net` records to `inchra-stats.inchra.net`
  * Get Avast to fix their anti-malware check.

**Comment by est31** [comment] 2015-09-12 03:11
You mean "Copy all the `amun.inchra.net` records to `inchra-stats.`**minetest**`.net`" don't you?

**Comment by ShadowNinja** [comment] 2015-09-13 01:44
Er, yes, of course.

**Comment by rubenwardy** [comment] 2016-02-05 22:49
Getting flagged by an AV is quite a major issue.

**Comment by ShadowNinja** [comment] 2016-02-12 06:00
Another idea: Enabling SSL might fix this -- the stats server is now ready for it.
Direct A/AAAA records aren't used yet though.
Is this even still an issue?  I haven't heard about anyone else getting malware warnings, it's been a while, and BrandonReese reported it as a false positive (posted to topic and awaiting reply).

**Comment by rubenwardy** [comment] 2016-02-13 23:16
This should get fixed soon, or the analytics should be removed.

**Comment by celeron55** [comment] 2016-02-26 09:42
I have now added stats.minetest.net which has A and AAAA records that point to the amun.inchra.net server (A=45.56.104.202, AAAA=2600:3c03::f03c:91ff:fe33:a4f8). Feel free to use.

**Comment by ShadowNinja** [comment] 2016-03-15 18:12
Fixed by 87b8ef9bc25e4ed69cda5369374d8ba2a89f99f2 as reported by DI3HARD139 in the linked forum thread.

**Closed by ShadowNinja** 2016-03-15 18:12 UTC
Labels: medium priority
