### ISSUE TITLE
Extend gallery

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#36] opened 2015-09-15 13:47 UTC
Here is a thread collecting screenshots specifically for the homepage:

https://forum.minetest.net/viewtopic.php?f=3&t=10366

Please consider adding some of these screenshots. Maybe on a seperate page or something.

Additionally, you may just link to this thread (and maybe, maybe the huge regular screenshot thread).

Edit: It might also be a good idea to collect the best screenshots and store them somewhere where they're safe, even if they might not be used instantly on the homepage. In the linked thread, at least one screenshot is already lost. :(

**Comment by Calinou** [comment] 2015-09-15 19:02
Screenshots should look good, have no licensing issues, so I can't afford taking random (potentially old) screenshots from the community.

**Comment by Wuzzy2** [comment] 2015-09-16 01:13
Bummer. This makes all submissions in this thread worthless, right?

Well, since you insist on it, here you go: You hereby have my permission to use my screenshot for whatever purpose you like to. WTFPL, if you will.

This is pretty much every screenshot in my first post in this thread, before the line that says “Now for some screenshots I repost here:”. I fear now you have to repeat that for about some dozen more users, have fun! xD

As for the size, settings and aspect ratio: Do you have any particular wishes for that?

**Comment by PilzAdam** [comment] 2015-09-16 17:10
@Wuzzy2 feel free to write a letter to your local government to tell them that the current copyright system is flawed. Until they change it we better don't use screenshots just because you think we are allowed to do so.

**Comment by ShadowNinja** [comment] 2015-09-19 05:43
@Calinou: Aren't different graphics settings good?  That way you can show more of the different graphics options.  Agreed on the other points though.

**Comment by Calinou** [comment] 2015-09-19 08:56
> Aren't different graphics settings good? That way you can show more of the different graphics options. Agreed on the other points though.

I can't think of any game that intentionally uses low graphics settings for official screenshots... Press is likely to take those as-is, and thus, they need to look as good as possible.

**Comment by rubenwardy** [comment] 2017-03-20 01:29
duplicate of #78 (closing this one as it has less content, even if it's older)

**Closed by rubenwardy** 2017-03-20 01:29 UTC
Labels: @content, enhancement
