### ISSUE TITLE
Homepage screenshot/background is a bit outdated (flat torch)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#152] opened 2019-01-10 19:36 UTC
The big screenshot / background on the homepage is a bit outdated.

https://www.minetest.net/media/background-home.jpg

It's outdated because it still shows the old flat torch.

Ideas for an update? Just reproduce the same scenery, but with 3D torch? Or maybe use an entirely different scenery?

**Comment by benrob0329** [comment] 2019-01-10 22:24
Maybe show a header with several games on it?

**Comment by Linuxdirk** [comment] 2019-02-28 15:38
> It's outdated

... and depressing. All screenshots look so dark and boring.

We have a shit-ton of cool and creative screenshots showing Minetest in all of it's glory in the forums. We just need a vote to find the maybe 10-15 best screenshots.

**Comment by benrob0329** [comment] 2019-02-28 16:54
Flightgear has a "screenshot of the month" competition on their forum. Basically users can submit their best screenshots throughout each month before the topic is closed and a poll opened with the submitted screenshots.

Something similar could help us gather some decent screenshots for the website (and possibly the header).

**Comment by Linuxdirk** [comment] 2019-03-01 12:29
> Flightgear has a "screenshot of the month" competition on their forum.

That would be a cool idea, but for some reasons the officials in the forums prefer unmaintainable mammoth threads instead of multiple smaller single-purpose threads.

Having such a contests means we need to have a screenshots section where such contests can be held and where people can post their screenshots in individual threads instead of a multiple hundreds of pages long single thread.

**Comment by rubenwardy** [comment] 2020-09-29 14:49
Duplicate of #78

**Closed by rubenwardy** 2020-09-29 14:49 UTC
