### ISSUE TITLE
Scrolling animations: annoying?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest.github.io#37] opened 2015-09-15 13:50 UTC
If you click an anchor link on the same page (“#” in URL) and have JavaScript enabled, the website “scrolls” around instead of instantly jumping to the ancor.

This seems to be a trend/hype in modern webdesign, and I hate it very much, as it is irritating to me. Who thinks the same way?

I want to have it disabled.

**Comment by est31** [comment] 2015-09-15 14:03
I honestly don't care whether it scrolls or not.

**Comment by Calinou** [comment] 2015-09-15 19:01
Animations are fine as long as they're fast enough, and this animation is fast enough. In fact, animations make experience better.

To compare, try playing Unvanquished as an alien with "Instant" wall-walking camera change. You'll get dizzy in seconds.

**Comment by Wuzzy2** [comment] 2015-09-16 01:49
> Animations are fine as long as they're fast enough, and this animation is fast enough.

By extension, the fastest “animation” is an instant change in location, which is of course no animation at all. :P

Haha, but now for reals:

> In fact, animations make experience better; they help you know where you are and what's happening.

Not for me, I find this very irritating. 
Also, you are forgetting that the animation delays the user interaction, so there is also a clear downside. It is this which ticks me off.

But whatever, I see that our opinions differ here. We are different users who like to use the web differently.

And this is a feature which could be *perfectly* well implemented by web browsers or at least one of their add-ons. If your browser is lacking such a feature, request it from the browser vendor.
This would also have the benefit that different web users (like you and me) can use the web they way they want to, and not the way the server operator wants to (what you are proposing).

> To compare, try playing Unvanquished as an alien with "Instant" wall-walking camera change. You'll get dizzy in seconds.

Calinou, you are comparing a website with a fast-paced first-person shooter. This is ridiculous. xD

**Comment by est31** [comment] 2015-09-16 13:00
@Wuzzy2 what you demand already exists, its a Web 1.0 feature, do some research. And the good message: we even support it. On firefox, you can access the feature with:

1. press alt to get the old menu bar on the top (I think this feature has been removed from the new design as firefox had their "design update" to make place for more important "features" like pocket)
1. go to View->Page Style->No Style

Then the website even works without any pesky javascript, and there are no scrolling animations reducing your productivity.

**Comment by Wuzzy2** [comment] 2015-09-16 15:41
This feature also disables all stylesheets whatsoever. That's not exactly what I've asked for.

So this is a hack, but not a solution. :-(

**Comment by est31** [comment] 2015-09-16 17:12
There are addons for finer control.

**Comment by ShadowNinja** [comment] 2015-09-19 05:35
I find the animations fine, although I'd probably be O.K. with a speed increase.

**Comment by cheapie** [comment] 2015-10-01 02:06
I'm fine with the # animations, just as long as it doesn't completely take over scrolling (sort of like what Google's "inbox" demo page thing does).

**Comment by Wuzzy2** [comment] 2015-10-02 17:10
est31: Ideally, websites just work without having to use any browser add-ons …
Heck, there are even browsers without any add-on support.

As I said, the scrolling animation is a non-standard feature. It is harder to disable a non-standard server-side imposed feature afterwards than to manually add a desired feature with add-ons.

There is another reason why I think this is a bad idea: What about browsers or browser add-ons which *already* implement this kind of scrolling when you click on any `#` anchor? There is no reason why a browser or browser add-on should *not* implement such a feature. As I said, such a thing would be a nice-to-have feature on the client side. It just does not go into my head why you insist this must be on the server-side.

But those browsers or browser add-ons are likely to fail on minetest.net because there would be now two “scrolling algorithms” competing against each other. So the safest approach is to leave scrolling entirely up to the browser and not mess around with it on the server-side.

Therefore, anyone who argues that this feature should be kept on minetest.net because they like it personally is missing the point.

**Comment by rubenwardy** [comment] 2015-10-03 10:07
That's not how it would work, Wuzzy. When clicking the anchor link it calls some Javascript code which scrolls. The default browser action is disabled.

That is, the javascript script overrides the links to call JS code rather than to scroll.

**Comment by cheapie** [comment] 2015-10-03 15:33
@rubenwardy That sounds entirely too much like reinventing the wheel there. "Instead of letting the browser scroll, we'll block it and scroll the page ourselves"

**Comment by rubenwardy** [comment] 2015-10-03 16:10
Browsers don't scroll, they jump. I've never used a browser which scrolls.

**Comment by tobyhinloopen** [comment] 2016-10-09 09:06
Scrolling animations are a violation of native browser functionality. Don't interfere with browser functionality.

**Comment by azekillDIABLO** [comment] 2017-06-05 11:03
Ummh. I don't have any animation on the site.

**Comment by octacian** [comment] 2017-06-21 13:48
Scrolling should stay in place. Not only does it look much nicer than jumping from place to place, but it also, as someone else mentioned, gives you a sense of where you are and where you are going. It is very common to override functions like scrolling via JavaScript, and there is nothing wrong with it whatsoever. All of you seem to have completely ignored the fact that JavaScript *is* client side, and runs on the browser. For this reason, it is perfectly fine to do things like this and is in no way a "violation of native browser functionality."

For that matter, literally, any browser has an option somewhere in advanced settings that let you disable JavaScript and therefore disable the far nicer scroller used on minetest.net. And if you don't mind installing a plugin, there are many available that will allow you to disable JavaScript just for specific websites.

**Comment by tobyhinloopen** [comment] 2017-06-22 06:25
I say we write a chrome patch that introduces smooth scrolling as native functionality

**Comment by Wuzzy2** [comment] 2017-06-22 07:03
@tobyhinloopen: Exactly. This scrolling nonsense must be a client-only feature, the website should not touch scrolling at all. Asking users to disable JS for this website is admitting that it is broken by default.

Firefox has this feature included already, is even enabled by default. Which makes including it on a server-side script even more pointless.

Please don't dictate the client how to behave. At least not like that. And as you can see, there is clear evidence that my opinion that this is a bad feature is *not* just a fringe opinion. Quite the contrary.

**Comment by octacian** [comment] 2017-06-22 19:16
> I say we write a chrome patch that introduces smooth scrolling as native functionality

I'm not against such a patch, but in order for this to be a solution, you have to remember the other browsers that exist today. And also remember, that not all of them are open source so you couldn't necessarily write patches for all.

Therefore the JavaScript implementation is best, as it will work for all Browsers, including those on mobile. My theory is that functionality on a website is best implemented so that it will be functional in the same way on all browsers, which sometimes means that what could be native to the browser will be overridden with JavaScript.

> Firefox has this feature included already, is even enabled by default. Which makes including it on a server-side script even more pointless.

I used Firefox for 2+ years before switching to Chrome about 8 months ago and never saw this feature. Is this something new?

> Asking users to disable JS for this website is admitting that it is broken by default.

Nobody asked you to disable JavaScript, only suggested that it is a possible solution if you are not interested in many of neat things that can be done using JavaScript. If some extra functionality is added using an optional language like JavaScript is added and somebody does not like that functionality, asking them to disable JS is not saying that the extra functionality is broken, it is simply giving them a method to avoid using the extra functionality which they do not like.

Yes, I'm aware that this does not yet *directly* apply to the Minetest website as JavaScript is required for the menu to work. However, this is *theoretically* applicable and once I have completed my pull request to retain full functionality without JavaScript, this will be *directly* applicable.

> Also, the problem is, this is a sever-side script...

JavaScript is stored on the server and sent to the client for execution. JavaScript can also be run strictly from the client, without being sent from the server. In the same manner, specific scripts from specific servers can on many browsers be ignored/disabled.

> Is it really that hard to understand why manipulating browser scrolling by a script provided by the server is a stupid idea which actually harms usability?

How could this possibly harm usability? Sure, instantly jumping from place to place does mean that you get there quicker, but by the time you get there you have no clue as to whether you jumped up or down without looking at the scrollbar. In other words, you entirely lose your sense of where you are on the page.

Until most browsers support smooth scrolling entirely client side, I will not support the removal of smooth scrolling from the minetest.net website, however, I would be perfectly happy to see smooth scrolling sped up a bit.

**Comment by Wuzzy2** [comment] 2017-06-22 19:52
Citing Jakob Nielson in <https://www.nngroup.com/articles/scrolling-and-scrollbars/>:

> The main guideline for a scrollbar's look-and-feel is simple: Use your platform's standard scrollbar, which is what users know and expect.

>  Scrollbars are easy to get right. In fact, the less work you do, the better your scrollbar. Usability is almost always enhanced when you use the built-in scrollbars rather than design your own.

Thus, intentionally deviating from the user expectations is bad.

> I'm not against such a patch, but in order for this to be a solution, you have to remember the other browsers that exist today. And also remember, that not all of them are open source so you couldn't necessarily write patches for all.

You are missing the point. At the end of the day, the *user* decides which browser to use.

> How could this possibly harm usability? Sure, instantly jumping from place to place does mean that you get there quicker, but by the time you get there you have no clue as to whether you jumped up or down without looking at the scrollbar. In other words, you entirely lose your sense of where you are on the page.
>
> Until most browsers support smooth scrolling entirely client side, I will not support the removal of smooth scrolling from the minetest.net website, however, I would be perfectly happy to see smooth scrolling sped up a bit.

Because it breaks with user expectations. User expectation is, when you click on an anchor link (i.e. a link inside the same webpage), it behaves however the browser behaves by default in this situation. Which is “jumping”.

And I dislike the tendency of websites trying to “fix” perceived browser problems. Just fix the browsers. Websites also have no say over where the URL bar or the back button is located. So why should they have *any* control over the scroll bar?

**Comment by tobyhinloopen** [comment] 2017-06-22 19:56
> I'm not against such a patch, but in order for this to be a solution, you have to remember the other browsers that exist today. And also remember, that not all of them are open source so you couldn't necessarily write patches for all.

I was joking.

> Therefore the JavaScript implementation is best, as it will work for all Browsers, including those on mobile. My theory is that functionality on a website is best implemented so that it will be functional in the same way on all browsers, which sometimes means that what could be native to the browser will be overridden with JavaScript.

Why not introduce an onscreen keyboard as well, in case you don't like the standard keyboard layout? Why let users have a standardised experience when you can override build-in behaviour without any obvious gain? I'd say, disable their keyboard and introduce an onscreen keyboard, just because you feel it is better that way. You can do that in Javascript as well, so it is still not interfering with native functionality, right?

**Comment by HybridDog** [comment] 2017-09-10 19:49
l can't reproduce the smooth scrolling.
l hate smooth scrolling because it delays interaction. l always disable them on android devices.
Smoothly scrolling down/up after clicking a hyperlink should be a browser setting. Otherwise it would be inconsistent, even here on ‮buhtig‭ 
there's no smooth hyperlink scrolling.

<details>
FYI: If you use firefox and a touchpad, you can enable pixel fine scrolling (linux):<br/>
Add <code>export MOZ_USE_XINPUT2=1</code> to ~/.profile<br/>
Open firefox and adjust scrolling speeds: in about:config set mousewheel.min_line_scroll_amount to 50, mouseWheel.durationMinMS to 5 and mouseWheel.durationMaxMS to 40.
</details>

**Comment by Calinou** [comment] 2017-09-10 20:29
> Smoothly scrolling down/up after clicking a hyperlink should be a browser setting.

No browser I know of supports this out of the box.

**Comment by HybridDog** [comment] 2017-09-11 08:13
They don't yet support it.

**Comment by rubenwardy** [comment] 2020-09-29 15:01
This should be fixed or closed

**Comment by rubenwardy** [comment] 2020-09-30 12:52
This no longer happens

**Closed by rubenwardy** 2020-09-30 12:52 UTC
Labels: @visuals, question
