### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest.github.io#196] opened 2019-11-20 13:12 UTC
Hi, i would like help translating the page to german. Is there a way to do it? I see no starts of translating

**Comment by Calinou** [comment] 2020-06-02 13:48
Jekyll doesn't feature proper internationalization support yet, so I don't think this would be a good idea unless we migrated the site to use [Hugo](https://gohugo.io/).

**Comment by rubenwardy** [comment] 2020-06-02 14:45
You don't necessarily need internationalization support. Minetest Modding Book is translated using folders, this makes sense as it's almost entirely text.

**Comment by rubenwardy** [comment] 2020-09-29 14:42
duplicate of #26

**Closed by rubenwardy** 2020-09-29 14:42 UTC
Labels: @content, enhancement
