### ISSUE TITLE
Add AppImage to Downloads Page

### ISSUE THREAD

**Issue by asddsaz** [minetest/minetest.github.io#154] opened 2019-02-20 04:12 UTC
**Feature**: Add AppImage to downloads page.
**Why?** AppImage is a great way for Linux users that do not have an official version of Minetest and cannot utilize Flatpak to run Minetest. Plus it is portable which is a bonus if a user wants to backup data.

Link to AppImage: https://forum.minetest.net/viewtopic.php?p=255946 (unofficial)
Version: 0.4.16

**Comment by Calinou** [comment] 2019-02-20 08:03
I think we should aim for having an official AppImage, so that it can stay up-to-date (mine is outdated right now).

Also, out of curiosity, which distributions can't run Flatpak but can run AppImages?

> Plus it is portable which is a bonus if a user wants to backup data.

User data is still placed in the usual locations when using an AppImage. An AppImage being "portable" only means that you can carry it around and run it without dependencies not present on a typical desktop Linux distribution.

**Comment by rubenwardy** [comment] 2023-05-08 13:46
duplicate of #270

(that has more discussion)

**Closed by rubenwardy** 2023-05-08 13:46 UTC
